version: '3'

services:
  pdan-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
    image: lostfan123/pdan-cpython:0.1.9-alpha
    volumes:
      - .:/opt/pdan
    stdin_open: true
    tty: true
