version: '3'

services:
  pdan-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
    image: lostfan123/pdan-cpython:0.1.0
    volumes:
      - ./pdan/:/opt/pdan/pdan/
      - ./tests/:/opt/pdan/tests/
      - ./README.md:/opt/pdan/README.md
      - ./pyproject.toml:/opt/pdan/pyproject.toml
      - ./pytest.ini:/opt/pdan/pytest.ini
    entrypoint: pytest
