MAX_COORDINATE_EXPONENT = 2  # 9
MAX_COORDINATE = 10 ** MAX_COORDINATE_EXPONENT
MIN_COORDINATE = -MAX_COORDINATE
MAX_DENOMINATOR = 3  # ** MAX_COORDINATE_EXPONENT
MAX_CONTOUR_SIZE = 5
MAX_REQUIREMENTS_COUNT = 3
MAX_HOLES_SIZE = 2

# MAX_COORDINATE_EXPONENT = 9
# MAX_COORDINATE = 10 ** MAX_COORDINATE_EXPONENT
# MIN_COORDINATE = -MAX_COORDINATE
# MAX_DENOMINATOR = 10 ** MAX_COORDINATE_EXPONENT
# MAX_CONTOUR_SIZE = None
